### ISSUE TITLE
[BUG] [VSCode Extension] Unable to create a new connection with Azure Open AI

### ISSUE THREAD

**Issue by kachely** [microsoft/promptflow#1009]
**Describe the bug**
Follow the guide to create a new connection with azure open AI. https://microsoft.github.io/promptflow/how-to-guides/manage-connections.html#create-a-connection
I have updated the yaml file.
<img width="609" alt="image" src="https://github.com/microsoft/promptflow/assets/20835886/1d917926-ad55-4495-b25c-b1c50545983c">
And input the API key in the terminal.
**But see below error messages.**
=================== Please input required secrets ===================
api_key: ********************************
=================== Required secrets collected ===================
Traceback (most recent call last):
  File "/mnt/workspace/promptflow/venv/lib/python3.11/site-packages/promptflow/_sdk/_utils.py", line 165, in _get_from_keyring
    return keyring.get_password(KEYRING_SYSTEM, KEYRING_ENCRYPTION_KEY_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/promptflow/venv/lib/python3.11/site-packages/keyring/core.py", line 56, in get_password
    return get_keyring().get_password(service_name, username)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/promptflow/venv/lib/python3.11/site-packages/keyring/backends/fail.py", line 28, in get_password
    raise NoKeyringError(msg)
keyring.errors.NoKeyringError: No recommended backend was available. Install a recommended 3rd party backend package; or, install the keyrings.alt package if you want to use the non-recommended backends. See https://pypi.org/project/keyring for details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ClickHouseAdmin/.vscode-server/extensions/prompt-flow.prompt-flow-1.3.1/pfutil/_pf_vsc_connection.py", line 52, in upsert_connection
    upsert_connection_new(args)
  File "/home/ClickHouseAdmin/.vscode-server/extensions/prompt-flow.prompt-flow-1.3.1/pfutil/_pf_vsc_connection.py", line 65, in upsert_connection_new
    connection = _upsert_connection_from_file(args.file)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/promptflow/venv/lib/python3.11/site-packages/promptflow/_cli/_pf/_connection.py", line 215, in _upsert_connection_from_file
    connection = _client.connections.create_or_update(connection)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/promptflow/venv/lib/python3.11/site-packages/promptflow/_telemetry/activity.py", line 138, in wrapper
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/promptflow/venv/lib/python3.11/site-packages/promptflow/_sdk/operations/_connection_operations.py", line 77, in create_or_update
    orm_object = connection._to_orm_object()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/promptflow/venv/lib/python3.11/site-packages/promptflow/_sdk/entities/_connection.py", line 277, in _to_orm_object
    secrets = self._validate_and_encrypt_secrets()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/promptflow/venv/lib/python3.11/site-packages/promptflow/_sdk/entities/_connection.py", line 153, in _validate_and_encrypt_secrets
    encrypt_secrets[k] = encrypt_secret_value(v)
                         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/promptflow/venv/lib/python3.11/site-packages/promptflow/_sdk/_utils.py", line 191, in encrypt_secret_value
    encryption_key = get_encryption_key(generate_if_not_found=True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/promptflow/venv/lib/python3.11/site-packages/promptflow/_sdk/_utils.py", line 174, in get_encryption_key
    ENCRYPTION_KEY_IN_KEY_RING = _get_from_keyring()
                                 ^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/promptflow/venv/lib/python3.11/site-packages/promptflow/_sdk/_utils.py", line 167, in _get_from_keyring
    raise StoreConnectionEncryptionKeyError(
promptflow._sdk._errors.StoreConnectionEncryptionKeyError: System keyring backend service not found in your operating system. See https://pypi.org/project/keyring/ to install requirement for different operating system, or 'pip install keyrings.alt' to use the third-party backend. Reach more detail about this error at https://microsoft.github.io/promptflow/how-to-guides/faq.html#connection-creation-failed-with-storeconnectionencryptionkeyerror

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ClickHouseAdmin/.vscode-server/extensions/prompt-flow.prompt-flow-1.3.1/pfutil/pfutil.py", line 4, in <module>
    main()
  File "/home/ClickHouseAdmin/.vscode-server/extensions/prompt-flow.prompt-flow-1.3.1/pfutil/_pf_vsc_main.py", line 35, in main
    operate_connection(args)
  File "/home/ClickHouseAdmin/.vscode-server/extensions/prompt-flow.prompt-flow-1.3.1/pfutil/_pf_vsc_connection.py", line 29, in operate_connection
    upsert_connection(args)
  File "/home/ClickHouseAdmin/.vscode-server/extensions/prompt-flow.prompt-flow-1.3.1/pfutil/_pf_vsc_connection.py", line 58, in upsert_connection
    connection = ConnectionOperations().create_or_update(connection)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/promptflow/venv/lib/python3.11/site-packages/promptflow/_telemetry/activity.py", line 138, in wrapper
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/promptflow/venv/lib/python3.11/site-packages/promptflow/_sdk/operations/_connection_operations.py", line 77, in create_or_update
    orm_object = connection._to_orm_object()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/promptflow/venv/lib/python3.11/site-packages/promptflow/_sdk/entities/_connection.py", line 277, in _to_orm_object
    secrets = self._validate_and_encrypt_secrets()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/workspace/promptflow/venv/lib/python3.11/site-packages/promptflow/_sdk/entities/_connection.py", line 155, in _validate_and_encrypt_secrets
    raise ValueError(f"Connection {self.name!r} secrets {invalid_secrets} value invalid, please fill them.")
ValueError: Connection 'edgechatbot-gpt-4' secrets ['api_key'] value invalid, please fill them.

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1. See above

**Screenshots**
1. On the VSCode primary side bar > the Prompt flow pane > quick access section. Find the "install dependencies" action. Please it and attach the screenshots there.
<img width="706" alt="image" src="https://github.com/microsoft/promptflow/assets/20835886/71ceabe2-de63-4d6c-a72c-3c16cfac1c48">

2. Please provide other snapshots about the key steps to repro the issue.
See above

**Environment Information**
 - Promptflow Package Version using `pf -v`: 0.1.0b8
 - Operating System:  Ubuntu 18.04.6 LTS
 - Python Version using `python --version`: Python 3.11.3
 - VS Code version.
 - Prompt Flow extension version.
 - On the VS Code bottom pane > Output pivot > "prompt flow" channel, find the error message could be relevant to the issue and past them here. That would be helpful for our trouble shooting.
 - If your code to repro the issue is public and you want to share us, please share the link.

**Additional context**

**Comment by kachely** [comment]
Successfully added the connection after install a package `keyrings.alt` mentioned in the error message.

**Comment by nilboy** [comment]
Successfully added the connection after install a package keyrings.alt. And then change python keyring backend.
```
pip install keyrings.alt
export PYTHON_KEYRING_BACKEND=keyrings.alt.file.PlaintextKeyring
```
