### ISSUE TITLE
[BUG] Default tutorial doesn't run once containerized 

### ISSUE THREAD

**Issue by bengimblett** [microsoft/promptflow#1436]
**Describe the bug**
A clear and concise description of the bug.

The default tutorial here https://github.com/microsoft/promptflow/ creates a basic chat flow. This can be run locally. Once it's built and converted into a container it will not run 

**How To Reproduce the bug**
Steps to reproduce the behaviour, how frequent can you experience the bug:
1. Follow the tutorial to create the flow and create connection/ref deployment to LLM (in my case AZ AI Service), then build the flow to create "dist" folder
2. Use Docker to build an image from the dist folder
3. Docker run to test the built image

**Expected behaviour**

Simple flow runs through UI access

**Screenshots**

Following shows the error (see context below)

{'node_name': 'chat', 'error_type_and_message': "(EmptyLLMApiMapping) LLM api mapping is empty, please ensure 'promptflow-tools' package has been installed."}

(note the connection is created and the flow will run in VS Code locally e.g. through pf test)

**Running Information(please complete the following information):**
 - Promptflow Package Version using `pf -v`: [e.g. 0.0.102309906]
 promptflow                       1.1.1
 - Operating System: [e.g. Ubuntu 20.04, Windows 11]
 W11
 - Python Version using `python --version`: [e.g. python==3.10.12]
Python 3.11.3
**Additional context**

2023-12-08 15:56:08 start promptflow serving with worker_num: 8, worker_threads: 1
2023-12-08 15:56:09 [2023-12-08 15:56:09 +0000] [22] [INFO] Starting gunicorn 20.1.0
2023-12-08 15:56:09 [2023-12-08 15:56:09 +0000] [22] [INFO] Listening at: http://0.0.0.0:8080 (22)
2023-12-08 15:56:09 [2023-12-08 15:56:09 +0000] [22] [INFO] Using worker: sync
2023-12-08 15:56:09 [2023-12-08 15:56:09 +0000] [23] [INFO] Booting worker with pid: 23
2023-12-08 15:56:09 [2023-12-08 15:56:09 +0000] [25] [INFO] Booting worker with pid: 25
2023-12-08 15:56:09 [2023-12-08 15:56:09 +0000] [24] [INFO] Booting worker with pid: 24
2023-12-08 15:56:09 [2023-12-08 15:56:09 +0000] [26] [INFO] Booting worker with pid: 26
2023-12-08 15:56:09 [2023-12-08 15:56:09 +0000] [27] [INFO] Booting worker with pid: 27
2023-12-08 15:56:09 [2023-12-08 15:56:09 +0000] [28] [INFO] Booting worker with pid: 28
2023-12-08 15:56:09 [2023-12-08 15:56:09 +0000] [29] [INFO] Booting worker with pid: 29
2023-12-08 15:56:09 [2023-12-08 15:56:09 +0000] [30] [INFO] Booting worker with pid: 30
2023-12-08 15:57:31 [2023-12-08 15:57:31,820][promptflow][ERROR] - Promptflow serving app error: {'message': "Tool load failed in 'chat': (EmptyLLMApiMapping) LLM api mapping is empty, please ensure 'promptflow-tools' package has been installed.", 'messageFormat': "Tool load failed in '{node_name}': {error_type_and_message}", 'messageParameters': {'node_name': 'chat', 'error_type_and_message': "(EmptyLLMApiMapping) LLM api mapping is empty, please ensure 'promptflow-tools' package has been installed."}, 'referenceCode': <ErrorTarget.EXECUTOR: 'Executor'>, 'code': 'UserError', 'innerError': {'code': 'EmptyLLMApiMapping', 'innerError': None}}
2023-12-08 15:57:31 [2023-12-08 15:57:31,823][promptflow][ERROR] - Promptflow serving error traceback: Traceback (most recent call last):
2023-12-08 15:57:31   File "/opt/conda/envs/promptflow-serve/lib/python3.9/site-packages/promptflow/executor/_tool_resolver.py", line 146, in resolve_tool_by_node
2023-12-08 15:57:31     return self._resolve_llm_node(node, convert_input_types=convert_input_types)
2023-12-08 15:57:31   File "/opt/conda/envs/promptflow-serve/lib/python3.9/site-packages/promptflow/executor/_tool_resolver.py", line 225, in _resolve_llm_node
2023-12-08 15:57:31     raise EmptyLLMApiMapping()
2023-12-08 15:57:31 promptflow.executor._errors.EmptyLLMApiMapping: LLM api mapping is empty, please ensure 'promptflow-tools' package has been installed.
2023-12-08 15:57:31 
2023-12-08 15:57:31 The above exception was the direct cause of the following exception:
2023-12-08 15:57:31 
2023-12-08 15:57:31 Traceback (most recent call last):
2023-12-08 15:57:31   File "/opt/conda/envs/promptflow-serve/lib/python3.9/site-packages/flask/app.py", line 867, in full_dispatch_request
2023-12-08 15:57:31     rv = self.dispatch_request()
2023-12-08 15:57:31   File "/opt/conda/envs/promptflow-serve/lib/python3.9/site-packages/flask/app.py", line 852, in dispatch_request
2023-12-08 15:57:31     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
2023-12-08 15:57:31   File "/opt/conda/envs/promptflow-serve/lib/python3.9/site-packages/promptflow/_sdk/_serving/app.py", line 102, in score
2023-12-08 15:57:31     app.init_invoker_if_not_exist()
2023-12-08 15:57:31   File "/opt/conda/envs/promptflow-serve/lib/python3.9/site-packages/promptflow/_sdk/_serving/app.py", line 65, in init_invoker_if_not_exist
2023-12-08 15:57:31     self.flow_invoker = FlowInvoker(
2023-12-08 15:57:31   File "/opt/conda/envs/promptflow-serve/lib/python3.9/site-packages/promptflow/_sdk/_serving/flow_invoker.py", line 64, in __init__
2023-12-08 15:57:31     self._init_executor()
2023-12-08 15:57:31   File "/opt/conda/envs/promptflow-serve/lib/python3.9/site-packages/promptflow/_sdk/_serving/flow_invoker.py", line 106, in _init_executor
2023-12-08 15:57:31     self.executor = FlowExecutor._create_from_flow(
2023-12-08 15:57:31   File "/opt/conda/envs/promptflow-serve/lib/python3.9/site-packages/promptflow/executor/flow_executor.py", line 233, in _create_from_flow
2023-12-08 15:57:31     resolved_tools = [tool_resolver.resolve_tool_by_node(node) for node in flow.nodes]
2023-12-08 15:57:31   File "/opt/conda/envs/promptflow-serve/lib/python3.9/site-packages/promptflow/executor/flow_executor.py", line 233, in <listcomp>
2023-12-08 15:57:31     resolved_tools = [tool_resolver.resolve_tool_by_node(node) for node in flow.nodes]
2023-12-08 15:57:31   File "/opt/conda/envs/promptflow-serve/lib/python3.9/site-packages/promptflow/executor/_tool_resolver.py", line 158, in resolve_tool_by_node
2023-12-08 15:57:31     raise ResolveToolError(node_name=node.name, target=e.target, module=e.module) from e
2023-12-08 15:57:31 promptflow.executor._errors.ResolveToolError: Tool load failed in 'chat': (EmptyLLMApiMapping) LLM api mapping is empty, please ensure 'promptflow-tools' package has been installed.
2023-12-08 15:57:31

**Comment by 0mza987** [comment]
Hi @bengimblett ,
Thanks for your feedback, `promptflow-tools` is indeed a necessary package when using `promptflow`, you can see they are both mentioned in the default installation guideline:
![image](https://github.com/microsoft/promptflow/assets/2572521/d3d60d50-79f8-41d1-9cb2-efccac3f2a7d)

**Comment by bengimblett** [comment]
Thanks @0mza987 ... yes ... as a 'newbie' to this I wasn't sure if the "promptflow-tools" was only required for the _developer_ and not the _distribution_. Thank you for confirming

**Comment by 0mza987** [comment]
@bengimblett You're welcome! We appreciate receiving feedback from the community, and we're always open to hearing more. Feel free to share any additional feedback or suggestions you may have. We value your input and look forward to hearing from you again soon.
