### ISSUE TITLE
[BUG] Promptflow Run with Automatic Runtime not working for AzureUSGovernment

### ISSUE THREAD

**Issue by mmclende** [microsoft/promptflow#1692]
**Describe the bug**
When attempting to do a run from the PFClient using an AML workspace in AzureUSGovernment I am getting a 401 Invalid Token error when it attempts to create_flow_session. I believe this may be due to using a wrong endpoint somewhere in the rest client code but I have been unable to verify this. Same code works fine with a PFClient pointed to an AML Workspace in Azure Commercial Cloud. 

**How To Reproduce the bug**
1. Perform an az login to ensure your azure credentials can be found by DefaultAzureCredential
2. Create Azure MLClient
3. Get AML workspace from client
4. Create PFClient using AML workspace
5. Perform a run using an automatic runtime

**Expected behavior**
Run is created on the AML workspace and a new runtime is created. Instead I get the following error:
```python
[promptflow][WARNING] - You're using automatic runtime, if it's first time you're using it, it may take a while to build runtime and request may fail with timeout error. Wait a while and resubmit same flow can successfully start the run.
Traceback (most recent call last):
  File "/Users/user1/anaconda3/lib/python3.11/site-packages/promptflow/azure/_restclient/flow_service_caller.py", line 58, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user1/anaconda3/lib/python3.11/site-packages/promptflow/azure/_restclient/flow_service_caller.py", line 478, in create_flow_session
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/Users/user1/anaconda3/lib/python3.11/site-packages/azure/core/exceptions.py", line 165, in map_error
    raise error
azure.core.exceptions.ClientAuthenticationError: (UserError) Invalid token
Code: UserError
Message: Invalid token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/user1/test.py", line 78, in <module>
    pipeline_job = pf.runs.create_or_update(run, stream=True, environment_variables={"AZUREML_CURRENT_CLOUD": "AzureUSGovernment"})
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user1/anaconda3/lib/python3.11/site-packages/promptflow/_telemetry/activity.py", line 138, in wrapper
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user1/anaconda3/lib/python3.11/site-packages/promptflow/azure/operations/_run_operations.py", line 224, in create_or_update
    rest_obj = self._resolve_dependencies_in_parallel(run=run, runtime=kwargs.get("runtime"), reset=reset)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user1/anaconda3/lib/python3.11/site-packages/promptflow/azure/operations/_run_operations.py", line 920, in _resolve_dependencies_in_parallel
    task_results = [task.result() for task in tasks]
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user1/anaconda3/lib/python3.11/site-packages/promptflow/azure/operations/_run_operations.py", line 920, in <listcomp>
    task_results = [task.result() for task in tasks]
                    ^^^^^^^^^^^^^
  File "/Users/user1/anaconda3/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/user1/anaconda3/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/Users/user1/anaconda3/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user1/anaconda3/lib/python3.11/site-packages/promptflow/azure/operations/_run_operations.py", line 906, in _resolve_runtime
    runtime = self._resolve_automatic_runtime(run=run, session_id=session_id, reset=reset)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user1/anaconda3/lib/python3.11/site-packages/promptflow/azure/operations/_run_operations.py", line 898, in _resolve_automatic_runtime
    self._resolve_session(run=run, session_id=session_id, reset=reset)
  File "/Users/user1/anaconda3/lib/python3.11/site-packages/promptflow/azure/operations/_run_operations.py", line 883, in _resolve_session
    self._service_caller.create_flow_session(
  File "/Users/user1/anaconda3/lib/python3.11/site-packages/promptflow/azure/_restclient/flow_service_caller.py", line 60, in wrapper
    raise FlowRequestException(
promptflow.azure._restclient.flow_service_caller.FlowRequestException: Calling create_flow_session failed with request id: b43ae1a5-b4ea-48cd-9dbf-6f732f1f8cf6 
Status code: 401 
Reason: Invalid token 
Error message: (UserError) Invalid token
Code: UserError
Message: Invalid token 
```

**Running Information(please complete the following information):**
 - Promptflow Package Version using `pf -v`: 1.1.1
 - Operating System: MacOSX 14.2
 - Python Version using `python --version`: 3.11.4

**Additional context**
I have tried passing in an environment variable called AZUREML_CURRENT_CLOUD but haven't seen a change in output. Here is the source code for reference:
```python
from azure.identity import DefaultAzureCredential
from azure.ai.ml import MLClient
from promptflow.entities import Run
from promptflow.azure import PFClient
from azure.identity import AzureAuthorityHosts

kwargs = {"cloud": "AzureUSGovernment"}
ml_client = MLClient(
        DefaultAzureCredential(authority=AzureAuthorityHosts.AZURE_GOVERNMENT),
        subscription_id,
        resource_group_name,
        workspace_name,
        **kwargs        
    )
workspace = ml_client.workspaces.get(name=workspace_name)
kwargs2 = {"ml_client": ml_client,"cloud": "AzureUSGovernment"}
pf = PFClient(
        DefaultAzureCredential(authority=AzureAuthorityHosts.AZURE_GOVERNMENT),
        subscription_id,
        resource_group_name,
        workspace_name,
        **kwargs2
    )
run = Run(
    flow=flow,
    data=data_id,
    resources={"instance_type": "Standard_E4ds_v4"},
    name=f"{experiment_name}_{timestamp}_{data_ref}",
    display_name=f"{experiment_name}_{timestamp}_{data_ref}",
    environment_variables={
        "AZUREML_CURRENT_CLOUD": "AzureUSGovernment"
        },
    column_mapping=exp_config_node,
    tags={
        "build_id": build_id
        },
)
pipeline_job = pf.runs.create_or_update(run, stream=True , environment_variables={"AZUREML_CURRENT_CLOUD": "AzureUSGovernment"})
```

**Comment by Stephen1993** [comment]
ack, I will investigate this issue.

**Comment by Stephen1993** [comment]
We currently only support public regions. I have created a task and plan to develop a code to support usgovernment.

**Comment by mmclende** [comment]
@Stephen1993 Is there a public issue or task associated that I can track the work with?

**Comment by mmclende** [comment]
It looks like when you get the token for headers you are hard coding the commercial endpoint
```python
def _get_headers(self):
        token = self._credential.get_token("https://management.azure.com/.default")
```

I am looking into if there's an easy way to fix that, if so I will look into opening a PR

**Comment by mmclende** [comment]
@Stephen1993 Looks like you may have fixed this already via this PR https://github.com/microsoft/promptflow/pull/1706. Is there a version I can try to pull locally to test?

**Comment by agonzalez2014** [comment]
[like]  Adrian Gonzalez reacted to your message:
________________________________

**Comment by mmclende** [comment]
This was fixed via https://github.com/microsoft/promptflow/pull/1706
