### ISSUE TITLE
DefaultAzureCredential is not supported in the browser. Use InteractiveBrowserCredential instead.

### ISSUE THREAD

**Issue by motorreiziger** [microsoft/promptflow#1771]
**Describe the bug**
When I Try to update the connections in the connection pane, the error DefaultAzureCredential is not supported in the browser. Use InteractiveBrowserCredential instead. appears in vscode

**How To Reproduce the bug**
Refresh connections
 
![afbeelding](https://github.com/microsoft/promptflow/assets/7812893/1c3fcc9a-0a13-4874-a1c5-4b60896d83ec)

**Environment Information**
promptflow
installed version:
1.3.0
promptflow-tools
installed version:
1.0.3
OS windows 10

 - VS Code version: 1.85.1
Python 3.9.18

- I reinstalled the extension, login via az login succesful. 
- Installed Azure ML extention and logged in.

**Comment by JYC-99** [comment]
@motorreiziger 
please find the prompt flow config file at this path: ~/.promptflow/pf.yaml
- in case you intend to use the connections in your local sqlite, please set the connection provider to local

```yaml
connection:
  provider: local
```

- in case you want to use aml workspace or ai studio connections, please install the [Azure CLI](https://learn.microsoft.com/en-us/cli/azure/) and to ```az login``` to get the credential for your device.

Please read the doc for more information:
more about connections: https://microsoft.github.io/promptflow/how-to-guides/manage-connections.html
more about how to set connection provider: https://microsoft.github.io/promptflow/how-to-guides/set-global-configs.html#connection-provider

**Comment by motorreiziger** [comment]
Hi @JYC-99,
Thank you for your prompt reply, We have tried the options you mentioned, but the error persists.
Strangely I've managed to get the flow working, but with the error.

**I've Looked up the logging and this is what i found**
2024-01-18 13:25:46.446 [info] C:\Users\name\.conda\envs\z6\python.exe c:\Users\name\.vscode\extensions\prompt-flow.prompt-flow-1.9.0\pfutil\pfutil.py tool --list -o C:\Users\name\AppData\Local\Temp\pf-listTools-624856c7-8efb-46f3-a448-55661abc2f98.json
2024-01-18 13:25:46.468 [error] Error: DefaultAzureCredential is not supported in the browser. Use InteractiveBrowserCredential instead.
    at Object.<anonymous> (c:\Users\name\.vscode\extensions\prompt-flow.prompt-flow-1.9.0\extension-FP-uhUXc.js:34113:1551)
    at Module.o._compile (c:\Users\name\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:1271)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1371:10)
    at Module.load (node:internal/modules/cjs/loader:1171:32)
    at Module._load (node:internal/modules/cjs/loader:1012:12)
    at Function.f._load (node:electron/js2c/asar_bundle:2:13377)
    at Function.c._load (c:\Users\name\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:171:5632)
    at Function.n._load (c:\Users\name\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:168:29551)
    at Function.t._load (c:\Users\name\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:133:35226)
    at Module.require (node:internal/modules/cjs/loader:1195:19)
    at h (c:\Users\name\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:647)
    at Module.<anonymous> (c:\Users\name\.vscode\extensions\prompt-flow.prompt-flow-1.9.0\extension.js:1:151)
    at Module.o._compile (c:\Users\name\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:4:1271)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1371:10)
    at Module.load (node:internal/modules/cjs/loader:1171:32)
    at Module._load (node:internal/modules/cjs/loader:1012:12)
    at Function.f._load (node:electron/js2c/asar_bundle:2:13377)
    at Function.c._load (c:\Users\name\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:171:5632)
    at Function.n._load (c:\Users\name\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:168:29551)
    at Function.t._load (c:\Users\name\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:133:35226)
    at Module.require (node:internal/modules/cjs/loader:1195:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Function.i [as __$__nodeRequire] (c:\Users\name\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:5:98)
    at f.vb (c:\Users\name\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:168:30730)
    at async Promise.all (index 0)

**Comment by JYC-99** [comment]
@motorreiziger Thanks for reporting this. A new version 1.9.1 is live now to fix this issue. Please try upgrading your extension on VS Code.

**Comment by motorreiziger** [comment]
> @motorreiziger Thanks for reporting this. A new version 1.9.1 is live now to fix this issue. Please try upgrading your extension on VS Code.

@JYC-99 It's working fine now, thank you!
