### ISSUE TITLE
No module named 'yaml'

### ISSUE THREAD

**Issue by ZhiliangWu** [microsoft/promptflow#1812]
**Describe the bug**
`pf flow validate --source <path-to-flow>` show warning as 

```console
[2024-01-22 11:35:45,390][promptflow._core.tools_manager][WARNING] - Failed to load tools from package promptflow-tools: No module named 'yaml', traceback: Traceback (most recent call last):
  File "/********/bug-prompt/.venv/lib/python3.9/site-packages/promptflow/_core/tools_manager.py", line 79, in collect_package_tools
    list_tool_func = entry_point.load()
  File "/********/bug-prompt/.venv/lib/python3.9/site-packages/importlib_metadata/__init__.py", line 184, in load
    module = import_module(match.group('module'))
  File "/********/.pyenv/versions/3.9.10/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/********/bug-prompt/.venv/lib/python3.9/site-packages/promptflow/tools/list.py", line 3, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'

{
  "result": "Succeeded"
}
```

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1. Install the package with poetry using `poetry add promptflow promptflow-tools` (or `pip install promptflow promptflow-tools`)
2. Create a flow with `pf flow init --flow flow-standard --type standard`
3. Validate the flow `pf flow validate --source flow-standard`

**Expected behavior**
`yaml` should be added as a dependency for the `promptflow-tools`.

**Screenshots**

**Running Information(please complete the following information):**
 - Promptflow Package Version using `pf -v`: 1.4.0
 - Operating System: MacOS 14.2.1
 - Python Version using `python --version`: 3.9.10

**Additional context**

**Comment by chjinche** [comment]
Hi @ZhiliangWu could you please retry by installing latest pf-tools `pip install promptflow-tools==1.1.0`? consistent with latest pf, pf-tools also changes from `pyyaml` to `ruamel.yaml`.
