### ISSUE TITLE
[BUG] Building executable app fails on Linux machine

### ISSUE THREAD

**Issue by anderl80** [microsoft/promptflow#2905]
**Describe the bug**
Try to run https://github.com/microsoft/promptflow/tree/main/examples/tutorials/flow-deploy/distribute-flow-as-executable-app on a Linux machine (devcontainer) results in pf trying to build executables for Windows machine. This results in Python package pywin32 being not installable.

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1. `pf flow build --source ./my_flow --output my_target --format executable`

**Expected behavior**
App exec for Linux i  built

**Screenshots**
```bash
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/importlib/metadata/__init__.py", line 563, in from_name
    return next(cls.discover(name=name))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pyinstaller", line 8, in <module>
    sys.exit(_console_script_run())
             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/PyInstaller/__main__.py", line 228, in _console_script_run
    run()
  File "/usr/local/lib/python3.11/site-packages/PyInstaller/__main__.py", line 212, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/usr/local/lib/python3.11/site-packages/PyInstaller/__main__.py", line 69, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/PyInstaller/building/build_main.py", line 1186, in main
    build(specfile, distpath, workpath, clean_build)
  File "/usr/local/lib/python3.11/site-packages/PyInstaller/building/build_main.py", line 1126, in build
    exec(code, spec_namespace)
  File "app.spec", line 18, in <module>
    datas += copy_metadata(package)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/PyInstaller/utils/hooks/__init__.py", line 957, in copy_metadata
    dist = importlib_metadata.distribution(package_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/metadata/__init__.py", line 982, in distribution
    return Distribution.from_name(distribution_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/metadata/__init__.py", line 565, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for pywin32
Traceback (most recent call last):
  File "/usr/local/bin/pf", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/promptflow/_cli/pf.py", line 14, in main
    _main()
  File "/usr/local/lib/python3.11/site-packages/promptflow/_cli/_pf/entry.py", line 169, in main
    entry(command_args)
  File "/usr/local/lib/python3.11/site-packages/promptflow/_cli/_pf/entry.py", line 133, in entry
    cli_exception_and_telemetry_handler(run_command, activity_name)(args)
  File "/usr/local/lib/python3.11/site-packages/promptflow/_cli/_utils.py", line 379, in wrapper
    raise e
  File "/usr/local/lib/python3.11/site-packages/promptflow/_cli/_utils.py", line 367, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/promptflow/_cli/_pf/entry.py", line 87, in run_command
    raise ex
  File "/usr/local/lib/python3.11/site-packages/promptflow/_cli/_pf/entry.py", line 61, in run_command
    dispatch_flow_commands(args)
  File "/usr/local/lib/python3.11/site-packages/promptflow/_cli/_pf/_flow.py", line 80, in dispatch_flow_commands
    build_flow(args)
  File "/usr/local/lib/python3.11/site-packages/promptflow/_cli/_pf/_flow.py", line 627, in build_flow
    pf_client.flows.build(
  File "/usr/local/lib/python3.11/site-packages/promptflow/_sdk/_telemetry/activity.py", line 265, in wrapper
    return f(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/promptflow/_sdk/operations/_flow_operations.py", line 732, in build
    self._build_as_executable(
  File "/usr/local/lib/python3.11/site-packages/promptflow/_sdk/operations/_flow_operations.py", line 622, in _build_as_executable
    self._run_pyinstaller(output_dir)
  File "/usr/local/lib/python3.11/site-packages/promptflow/_sdk/operations/_flow_operations.py", line 643, in _run_pyinstaller
    subprocess.run(["pyinstaller", "app.spec"], check=True)
  File "/usr/local/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['pyinstaller', 'app.spec']' returned non-zero exit status 1.
```

**Running Information(please complete the following information):**
 - Promptflow Package Version using `pf -v`: [e.g. 0.0.102309906]
 > promptflow                       1.8.0
> promptflow-tracing               1.8.0
> promptflow-core                  1.8.0
> promptflow-devkit                1.8.0
>
> Executable '/usr/local/bin/python'
> Python (Linux) 3.11.9 (main, Apr 10 2024, 04:38:20) [GCC 12.2.0]
 - Operating System: [e.g. Ubuntu 20.04, Windows 11]
> FROM python:3.11-slim
 - Python Version using `python --version`: [e.g. python==3.10.12]
> Python 3.11.9

**Comment by YingChen1996** [comment]
Hi, @anderl80. Thanks for reporting the issue. According to the stack trace, it seems we add pywin32 as the hidden import and collect its metafile for Pyinstaller to pack. 
![image](https://github.com/microsoft/promptflow/assets/26239730/0f81dac5-4f0d-4b05-b90a-94d9f3c7e83e)
But it's not required in linux machine, we will fix it soon and as a workaround, you can find the installation dir of promptflow and remove `pywin32` in the "promptflow/_sdk/data/executable/requirements.txt"

**Comment by YingChen1996** [comment]
Fixed PR has merged.
