### ISSUE TITLE
ImportError: DLL load failed while importing _rust: The specified procedure could not be found

### ISSUE THREAD

**Issue by tyler-suard-parker** [microsoft/promptflow#3374]
**Describe the bug**
I am trying to set the trace destination using the code given in the tutorial.  I am getting this error:

    from cryptography.hazmat.bindings._rust import exceptions as rust_exceptions
ImportError: DLL load failed while importing _rust: The specified procedure could not be found

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1. Download trace-autogen-groupchat.ipynb
2. pip install promptflow promtpflow-tools
3. az login
4. pf config set trace.destination=(my trace destination)

The error occurs here.

**Expected behavior**
I expect the steps in the instructions to work.  I expected the trace destination in my config to be set without any errors.

**Comment by tyler-suard-parker** [comment]
Complete trace:

Traceback (most recent call last):
  File "c:\users\945764\write_unit_tests\productgpt2\.venv\lib\site-packages\promptflow\__init__.py", line 17, in <module>
    from promptflow._sdk._load_functions import load_flow as _load_flow
  File "c:\users\945764\write_unit_tests\productgpt2\.venv\lib\site-packages\promptflow\_sdk\_load_functions.py", line 15, in <module>
    from .entities import Run
  File "c:\users\945764\write_unit_tests\productgpt2\.venv\lib\site-packages\promptflow\_sdk\entities\__init__.py", line 8, in <module>
    from ._connection import (
  File "c:\users\945764\write_unit_tests\productgpt2\.venv\lib\site-packages\promptflow\_sdk\entities\_connection.py", line 25, in <module>
    from promptflow._sdk._orm.connection import Connection as ORMConnection
  File "c:\users\945764\write_unit_tests\productgpt2\.venv\lib\site-packages\promptflow\_sdk\_orm\__init__.py", line 7, in <module>
    from promptflow._sdk._orm.run_info import RunInfo
  File "c:\users\945764\write_unit_tests\productgpt2\.venv\lib\site-packages\promptflow\_sdk\_orm\run_info.py", line 23, in <module>
    from .session import mgmt_db_session
  File "c:\users\945764\write_unit_tests\productgpt2\.venv\lib\site-packages\promptflow\_sdk\_orm\session.py", line 34, in <module>
    from promptflow._sdk._utilities.general_utils import (
  File "c:\users\945764\write_unit_tests\productgpt2\.venv\lib\site-packages\promptflow\_sdk\_utilities\general_utils.py", line 31, in <module>
    from cryptography.fernet import Fernet
  File "c:\users\945764\write_unit_tests\productgpt2\.venv\lib\site-packages\cryptography\fernet.py", line 14, in <module>
    from cryptography.exceptions import InvalidSignature
  File "c:\users\945764\write_unit_tests\productgpt2\.venv\lib\site-packages\cryptography\exceptions.py", line 9, in <module>
    from cryptography.hazmat.bindings._rust import exceptions as rust_exceptions
ImportError: DLL load failed while importing _rust: The specified procedure could not be found.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\945764\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\945764\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\945764\write_unit_tests\ProductGPT2\.venv\Scripts\pf.exe\__main__.py", line 4, in <module>
    from promptflow._cli.pf import main
  File "c:\users\945764\write_unit_tests\productgpt2\.venv\lib\site-packages\promptflow\__init__.py", line 21, in <module>
    raise Exception(
Exception: Promptflow may not installed correctly. If you are upgrading from 'promptflow<1.8.0' to 'promptflow>=1.8.0', please run 'pip uninstall -y promptflow promptflow-core promptflow-devkit promptflow-azure', then 'pip install promptflow>=1.8.0'. Reach https://microsoft.github.io/promptflow/how-to-guides/faq.html#promptflow-1-8-0-upgrade-guide for more information.

**Comment by tyler-suard-parker** [comment]
I tried again with a new, clean venv.  I literally followed your exact instructions:
pip install promptflow promptflow-tools
pf flow init --flow ./my_chatbot --type chat

And I still got the exact same error.

**Comment by tyler-suard-parker** [comment]
Upgrading via pip did not help.

I did not git clone the repo, because I don't want to have to combine your code base with mine to get things to work.

**Comment by tyler-suard-parker** [comment]
I solved this issue by completely uninstalling Python 3.9 and using python 3.11 instead.
