### ISSUE TITLE
[BUG] prompt eval method does not take credential and creates PFClient without passing in credential

### ISSUE THREAD

**Issue by yanggaome** [microsoft/promptflow#3537]
**Describe the bug**
A clear and concise description of the bug.

https://github.com/microsoft/promptflow/blob/main/src/promptflow-evals/promptflow/evals/evaluate/_evaluate.py
credential is not available and not passed into PFClient

```
pf_client = PFClient(
        config={
            "trace.destination": _trace_destination_from_project_scope(azure_ai_project)} if azure_ai_project else None,
        user_agent=USER_AGENT,
    )
```

Update:
Looking into a bit more of the stack trace, looks like the exception was thrown from here from PFClient init method
https://github.com/microsoft/promptflow/blob/main/src/promptflow-azure/promptflow/azure/_pf_client.py#L68

```
        try:
            workspace = self._ml_client.workspaces.get(name=self._ml_client._operation_scope.workspace_name)
        except Exception as e:
            raise UserErrorException(message=str(e), error=e)
```

This is causing our runs to fail while trying to use managed identity

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.9/site-packages/promptflow/azure/_pf_client.py", line 68, in __init__
    workspace = self._ml_client.workspaces.get(name=self._ml_client._operation_scope.workspace_name)
  File "/usr/local/miniconda/lib/python3.9/site-packages/azure/ai/ml/_telemetry/activity.py", line 288, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/miniconda/lib/python3.9/site-packages/azure/core/tracing/decorator.py", line 94, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/usr/local/miniconda/lib/python3.9/site-packages/azure/ai/ml/operations/_workspace_operations.py", line 130, in get
    return super().get(workspace_name=name, **kwargs)
  File "/usr/local/miniconda/lib/python3.9/site-packages/azure/ai/ml/operations/_workspace_operations_base.py", line 85, in get
    obj = self._operation.get(resource_group, workspace_name)
  File "/usr/local/miniconda/lib/python3.9/site-packages/azure/core/tracing/decorator.py", line 94, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/usr/local/miniconda/lib/python3.9/site-packages/azure/ai/ml/_restclient/v2023_08_01_preview/operations/_workspaces_operations.py", line 931, in get
    pipeline_response = self._client._pipeline.run(  # pylint: disable=protected-access
  File "/usr/local/miniconda/lib/python3.9/site-packages/azure/core/pipeline/_base.py", line 229, in run
    return first_node.send(pipeline_request)
  File "/usr/local/miniconda/lib/python3.9/site-packages/azure/core/pipeline/_base.py", line 86, in send
    response = self.next.send(request)
  File "/usr/local/miniconda/lib/python3.9/site-packages/azure/core/pipeline/_base.py", line 86, in send
    response = self.next.send(request)
  File "/usr/local/miniconda/lib/python3.9/site-packages/azure/core/pipeline/_base.py", line 86, in send
    response = self.next.send(request)
  [Previous line repeated 2 more times]
  File "/usr/local/miniconda/lib/python3.9/site-packages/azure/mgmt/core/policies/_base.py", line 46, in send

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
    results = evaluate(
  File "/usr/local/miniconda/lib/python3.9/site-packages/promptflow/evals/evaluate/_telemetry/__init__.py", line 111, in wrapper
    result = func(*args, **kwargs)
  File "/usr/local/miniconda/lib/python3.9/site-packages/promptflow/evals/evaluate/_evaluate.py", line 365, in evaluate
    raise e
  File "/usr/local/miniconda/lib/python3.9/site-packages/promptflow/evals/evaluate/_evaluate.py", line 340, in evaluate
    return _evaluate(
  File "/usr/local/miniconda/lib/python3.9/site-packages/promptflow/evals/evaluate/_evaluate.py", line 401, in _evaluate
    input_data_df, target_generated_columns, target_run = _apply_target_to_data(
  File "/usr/local/miniconda/lib/python3.9/site-packages/promptflow/evals/evaluate/_evaluate.py", line 183, in _apply_target_to_data
    run = pf_client.run(
  File "/usr/local/miniconda/lib/python3.9/site-packages/promptflow/_sdk/_pf_client.py", line 301, in run
    return self._run(
  File "/usr/local/miniconda/lib/python3.9/site-packages/promptflow/_sdk/_pf_client.py", line 226, in _run
    return self.runs.create_or_update(run=run, **kwargs)
  File "/usr/local/miniconda/lib/python3.9/site-packages/promptflow/_sdk/_telemetry/activity.py", line 265, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/local/miniconda/lib/python3.9/site-packages/promptflow/_sdk/operations/_run_operations.py", line 135, in create_or_update
    created_run = RunSubmitter(client=self._client).submit(run=run, **kwargs)
  File "/usr/local/miniconda/lib/python3.9/site-packages/promptflow/_sdk/_orchestrator/run_submitter.py", line 52, in submit
    task_results = [task.result() for task in tasks]
  File "/usr/local/miniconda/lib/python3.9/site-packages/promptflow/_sdk/_orchestrator/run_submitter.py", line 52, in <listcomp>
    task_results = [task.result() for task in tasks]
  File "/usr/local/miniconda/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/miniconda/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/usr/local/miniconda/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/miniconda/lib/python3.9/site-packages/promptflow/_sdk/_orchestrator/run_submitter.py", line 301, in _initialize_async_run_uploader
    pfazure_client = self._initialize_pfazure_client(run=run, config=self._config)
  File "/usr/local/miniconda/lib/python3.9/site-packages/promptflow/_sdk/_orchestrator/run_submitter.py", line 288, in _initialize_pfazure_client
    return _get_azure_pf_client(
  File "/usr/local/miniconda/lib/python3.9/site-packages/promptflow/azure/_cli/_utils.py", line 109, in _get_azure_pf_client
    client = PFClient(ml_client=ml_client, logging_enable=debug)
  File "/usr/local/miniconda/lib/python3.9/site-packages/promptflow/azure/_pf_client.py", line 70, in __init__
    raise UserErrorException(message=str(e), error=e)
promptflow.exceptions.UserErrorException: ManagedIdentityCredential authentication unavailable, no response from the IMDS endpoint.

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1.

**Expected behavior**

**Screenshots**

![image](https://github.com/microsoft/promptflow/assets/11587940/e0c2d37f-d75f-435d-8d65-4d20c2031636)

and in the user call back, we use load_flow as function and then run the flow
f = load_flow()
f(xxx, with credential and project_scope passing in)

**Running Information(please complete the following information):**
 - Promptflow Package Version using `pf -v`: [e.g. 0.0.102309906]
 - Operating System: [e.g. Ubuntu 20.04, Windows 11]
 - Python Version using `python --version`: [e.g. python==3.10.12]

{
  "promptflow": "1.13.0",
  "promptflow-azure": "1.13.0",
  "promptflow-core": "1.13.0",
  "promptflow-devkit": "1.13.0",
  "promptflow-evals": "0.3.0",
  "promptflow-tracing": "1.13.0"
}

**Additional context**

**Comment by yanggaome** [comment]
can be closed. we managed to setup the credential correctly, seems not related to promptflow itself

**Comment by rfolkes** [comment]
Stumbling on the exact same thing here: may I ask how you managed to set the credentials?
