### ISSUE TITLE
[VSCode Extension] Error: 400 status code (no body)

### ISSUE THREAD

**Issue by vincentgiraud** [microsoft/promptflow#3608]
**Describe the bug**
When hitting 'Run' on a example.prompty file, I'm getting a `400 status code (no body)` error in the VSC console output.
But the `pf flow test example.prompty` works.

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1. Copy the prompt example from https://microsoft.github.io/promptflow/how-to-guides/develop-a-prompty/use-prompty-in-flow.html#consume-prompty-in-code
2. Open in VSC, edit to remove the history - else will get another error - and set configuration for your Azure OpenAI deployment. Or use [example.prompty.txt](https://github.com/user-attachments/files/16454321/example.prompty.txt) (and remove the .txt extension)
3. Click the Run button
4. Output throws a consistent `400 status code (no body)` error

**Environment Information**
 - Promptflow Package Version using: 1.14.0
 - Operating System: Windows 11
 - Python Version : 3.11.0
 - VS Code version: 1.91.1
 - Prompt Flow extension version: 
 - On the VS Code bottom pane > Output pivot > "prompt flow" channel, the error message is:
Call Stack: Error: Invalid prompt format
    at PromptyChatParser.invoke (c:\Users\vgiraud\.vscode\extensions\ms-toolsai.prompty-0.1.2024060511\packages\core\out\extension.js:18071:17)
    at PromptyChatParser.call (c:\Users\vgiraud\.vscode\extensions\ms-toolsai.prompty-0.1.2024060511\packages\core\out\extension.js:17948:27)
    at _InvokerFactory.call (c:\Users\vgiraud\.vscode\extensions\ms-toolsai.prompty-0.1.2024060511\packages\core\out\extension.js:17991:56)
    at Function.prepare (c:\Users\vgiraud\.vscode\extensions\ms-toolsai.prompty-0.1.2024060511\packages\core\out\extension.js:18188:34)
    at execute (c:\Users\vgiraud\.vscode\extensions\ms-toolsai.prompty-0.1.2024060511\packages\core\out\extension.js:93079:19)
    at c:\Users\vgiraud\.vscode\extensions\ms-toolsai.prompty-0.1.2024060511\packages\core\out\extension.js:93825:28

**Comment by vincentgiraud** [comment]
Workaround from https://github.com/microsoft/prompty/issues/8 even though `api_key` property is no longer in the spec. Moved the issue to https://github.com/microsoft/prompty/issues/54
