### ISSUE TITLE
[BUG] Index Lookup raises  Exception in search_function_execution.

### ISSUE THREAD

**Issue by pkpsomas** [microsoft/promptflow#3696]
**Description**
Index lookup step using Registered Inded and an existing index that works OK in Chat playground fails in prompt flow with the following error:
Run failed: Exception: Exception occured in search_function_execution.

Traceback (most recent call last):
  File "/azureml-envs/prompt-flow/runtime/lib/python3.9/site-packages/promptflow_vectordb/tool/utils/profiling.py", line 18, in measure_execution_time
    yield
  File "/azureml-envs/prompt-flow/runtime/lib/python3.9/site-packages/promptflow_vectordb/tool/common_index_lookup.py", line 63, in telemetry_wrapper
    search_result = search_func(query)
  File "/azureml-envs/prompt-flow/runtime/lib/python3.9/site-packages/promptflow_vectordb/tool/common_index_lookup_extensions/acs.py", line 113, in wrapper
    results = search_func(query)
  File "/azureml-envs/prompt-flow/runtime/lib/python3.9/site-packages/langchain_community/vectorstores/azuresearch.py", line 524, in hybrid_search_with_score
    docs = [
  File "/azureml-envs/prompt-flow/runtime/lib/python3.9/site-packages/langchain_community/vectorstores/azuresearch.py", line 527, in <listcomp>
    page_content=result.pop(FIELDS_CONTENT),
KeyError: None

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/azureml-envs/prompt-flow/runtime/lib/python3.9/site-packages/promptflow_vectordb/tool/utils/profiling.py", line 18, in measure_execution_time
    yield
  File "/azureml-envs/prompt-flow/runtime/lib/python3.9/site-packages/promptflow_vectordb/tool/common_index_lookup.py", line 133, in search
    results = [
  File "/azureml-envs/prompt-flow/runtime/lib/python3.9/site-packages/promptflow_vectordb/tool/common_index_lookup.py", line 133, in <listcomp>
    results = [
  File "/azureml-envs/prompt-flow/runtime/lib/python3.9/concurrent/futures/_base.py", line 609, in result_iterator
    yield fs.pop().result()
  File "/azureml-envs/prompt-flow/runtime/lib/python3.9/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/azureml-envs/prompt-flow/runtime/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/azureml-envs/prompt-flow/runtime/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/azureml-envs/prompt-flow/runtime/lib/python3.9/site-packages/promptflow_vectordb/tool/common_index_lookup.py", line 63, in telemetry_wrapper
    search_result = search_func(query)
  File "/azureml-envs/prompt-flow/runtime/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/azureml-envs/prompt-flow/runtime/lib/python3.9/site-packages/promptflow_vectordb/tool/utils/profiling.py", line 21, in measure_execution_time
    raise Exception(error_msg) from e
Exception: Exception occured in search_function_inner_execution.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/azureml-envs/prompt-flow/runtime/lib/python3.9/site-packages/promptflow/tracing/_trace.py", line 556, in wrapped
    output = func(*args, **kwargs)
  File "/azureml-envs/prompt-flow/runtime/lib/python3.9/site-packages/promptflow_vectordb/core/logging/utils.py", line 98, in wrapper
    res = func(*args, **kwargs)
  File "/azureml-envs/prompt-flow/runtime/lib/python3.9/site-packages/promptflow_vectordb/tool/common_index_lookup.py", line 133, in search
    results = [
  File "/azureml-envs/prompt-flow/runtime/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/azureml-envs/prompt-flow/runtime/lib/python3.9/site-packages/promptflow_vectordb/tool/utils/profiling.py", line 21, in measure_execution_time
    raise Exception(error_msg) from e
Exception: Exception occured in search_function_execution.

**How To Reproduce the bug**
Method 1: get a working Chat example with a Vector index and select Prompt Flow to Orchestrate and customize this setup with prompt flow.
Method 2: create a flow by selecting "Multi-Round Q&A on Your Data" 

**Expected behavior**
Expected behaviours is the complete successfully the index lookup.

**Screenshots**
![image](https://github.com/user-attachments/assets/bbaed70e-0dbd-4151-9c2d-0e42ee9723a1)

**Running Information(please complete the following information):**
 - Azure AI Studio
 - Module: promptflow.tools.aoai

**Additional context**

**Comment by vis23563456** [comment]
True. Only appears when multiple fields are added to content in Field mapping. Change it to one, and it works alright.

**Comment by pkpsomas** [comment]
> True. Only appears when multiple fields are added to content in Field mapping. Change it to one, and it works alright.

I don't understand where the "multiple fields refer." Please give me more detailed description.
Please note that the model was constructed automatically from a "Chat playground project" that works OK.

**Comment by tvdermeer** [comment]
I've got the same error when running the "Q&A on Your Data" out of the box flow together with AI search. My index lookup settings look the following: 

![Screenshot 2024-09-04 at 11 09 06](https://github.com/user-attachments/assets/2533ce1b-a0b2-4153-84b8-820c93b0c2bb)

The error is a little more specific, namely keyerror 'content' is given.

**Comment by vis23563456** [comment]
> > True. Only appears when multiple fields are added to content in Field mapping. Change it to one, and it works alright.
> 
> I don't understand where the "multiple fields refer." Please give me more detailed description. Please note that the model was constructed automatically from a "Chat playground project" that works OK.

@pkpsomas I agree that there is a discrepancy between chat playground and the prompt flow automatically created. By multiple fields, I mean 
![image](https://github.com/user-attachments/assets/a418123e-7ad4-4d32-86bd-fa8d05156623)

This in the prompt flow, is reflected in 'acs_content_field' of the 'querySearchResource' as comma separated fields leading to an error. When you recreate the prompt flow but with only one content field selected in the 'add your data' section of the chat playground, it works fine. Definitely a bug.

**Comment by vis23563456** [comment]
> I've got the same error when running the "Q&A on Your Data" out of the box flow together with AI search. My index lookup settings look the following:
> 
> ![Screenshot 2024-09-04 at 11 09 06](https://private-user-images.githubusercontent.com/16362123/364310098-2533ce1b-a0b2-4153-84b8-820c93b0c2bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0NDE4OTEsIm5iZiI6MTcyNTQ0MTU5MSwicGF0aCI6Ii8xNjM2MjEyMy8zNjQzMTAwOTgtMjUzM2NlMWItYTBiMi00MTUzLTg0YjgtODIwYzkzYjBjMmJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDA5MTk1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4NzlhNzI5N2RjZWE2YzhiYzZhYWZjNDBjNWZlNDBjMWRjZDNlMjA5YTYzYzYwNzg1M2VhN2E5ZjI4ZjUxYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QyYLkjXdMDMfSmQHGzHdPqu45_y4R91mYhvdJdWEE2o)
> 
> The error is a little more specific, namely keyerror 'content' is given.

I'm afraid, we'd need more information to debug. For starters, does the AI search index have the 'content' field?

**Comment by tvdermeer** [comment]
<img width="329" alt="image" src="https://github.com/user-attachments/assets/4ee9947d-d7ed-40ec-a69f-295b5fa4a07b">
yes, these are there and available to choose from in the Index lookup GUI

**Comment by tvdermeer** [comment]
got it figured out. In the AI search settings, the content was not set as 'retrievable'. Changing this solved the issue, will close.

**Comment by pkpsomas** [comment]
I retested the functionality in the latest version, and it works OK.
