### ISSUE TITLE
[BUG] vector_db_lookup should not require the vector field to be returned by the search

### ISSUE THREAD

**Issue by jessica-ern** [microsoft/promptflow#374]
**Describe the bug**
The vector_db_lookup tool for Azure Cognitive Search will throw a UserErrorException: KeyError if the vector_field is not included as part of the "select" search_params.  There are scenarios where you don't want to include the vectors with your search results because the vectors are so large compared to the rest of the response object.  The vector_db_lookup tool should support this option and not throw a KeyError.

**How To Reproduce the bug**
1. follow https://microsoft.github.io/promptflow/reference/tools-reference/vector_db_lookup_tool.html to set up a vector_db_lookup tool in your flow
2. Add the object `{"select":"field_name_1, field_name_2, etc,"}` to the search_params field.  Replace the list of field names with the names of retrievable fields in your Azure Cognitive Search Index.
3. Do NOT include the field name you entered for vector_field.  (in my screen shot, you will see that content_vector is not included in search_params.  If I include it, then the vector_search node will pass.)
4. attempt to run a vector search using the tool.

**Expected behavior**
The vector_db_lookup tool should return the search response without throwing a KeyError

**Screenshots**
<img width="1241" alt="Screenshot 2023-09-12 at 4 27 32 PM" src="https://github.com/microsoft/promptflow/assets/107070686/41107575-a5b9-48d6-9805-515a32ad06ac">

<img width="824" alt="Screenshot 2023-09-12 at 4 30 17 PM" src="https://github.com/microsoft/promptflow/assets/107070686/41a82f7d-c049-4997-b64a-5f1d904b0fc7">

**Running Information:**
 - Promptflow Package Version using 0.1.0b5
 - promptflow-vectordb: 0.1.1
 - Operating System: MacOS
 - Python Version using 3.10.4
 - VS Code version 1.80.1
 - Prompt Flow extension version 1.0.7

logs:
```
2023-09-12 16:26:38 -0500   79043 promptflow_vectordb.tool INFO     [VectorDBLookup] EmbeddingStore.Tool.Init started
2023-09-12 16:26:38 -0500   79043 promptflow_vectordb.service INFO     [VectorDBLookup] EmbeddingStore.Client.Init started
2023-09-12 16:26:38 -0500   79043 promptflow_vectordb.service INFO     [VectorDBLookup] Agent instance: CogSearchClient initialized
2023-09-12 16:26:38 -0500   79043 promptflow_vectordb.service INFO     [VectorDBLookup] EmbeddingStore.Client.Init completed
2023-09-12 16:26:38 -0500   79043 promptflow_vectordb.tool INFO     [VectorDBLookup] Adapter instance: ConnectionBasedAdapter initialized
2023-09-12 16:26:38 -0500   79043 promptflow_vectordb.service INFO     [VectorDBLookup] EmbeddingStore.Client.Load started
2023-09-12 16:26:38 -0500   79043 promptflow_vectordb.service INFO     [VectorDBLookup] EmbeddingStore.Client.Load completed
2023-09-12 16:26:38 -0500   79043 promptflow_vectordb.tool INFO     [VectorDBLookup] EmbeddingStore.Tool.Init completed
2023-09-12 16:26:39 -0500   79043 promptflow_vectordb.tool INFO     [VectorDBLookup] EmbeddingStore.Tool.Search started
2023-09-12 16:26:39 -0500   79043 promptflow_vectordb.service INFO     [VectorDBLookup] EmbeddingStore.Client.SearchByEmbedding started
2023-09-12 16:26:39 -0500   79043 promptflow_vectordb.service INFO     [VectorDBLookup] EmbeddingStore.Client.SearchByEmbedding failed
2023-09-12 16:26:39 -0500   79043 promptflow_vectordb.tool INFO     [VectorDBLookup] EmbeddingStore.Tool.Search failed
Traceback (most recent call last):
  File "/Users/jessicaern/.pyenv/versions/3.10.4/lib/python3.10/site-packages/promptflow_vectordb/core/utils/retry_utils.py", line 19, in wrapper
    return func(*args, **kwargs)
  File "/Users/jessicaern/.pyenv/versions/3.10.4/lib/python3.10/site-packages/promptflow_vectordb/tool/vector_db_lookup.py", line 106, in search
    return _do_search()
  File "/Users/jessicaern/.pyenv/versions/3.10.4/lib/python3.10/site-packages/promptflow_vectordb/core/logging/utils.py", line 97, in wrapper
    res = func(*args, **kwargs)
  File "/Users/jessicaern/.pyenv/versions/3.10.4/lib/python3.10/site-packages/promptflow_vectordb/tool/vector_db_lookup.py", line 93, in _do_search
    return self.__adapter.search(
  File "/Users/jessicaern/.pyenv/versions/3.10.4/lib/python3.10/site-packages/promptflow_vectordb/tool/adapter/connection_based_adapter.py", line 60, in search
    obj_list = self.__store.search_by_embedding(
  File "/Users/jessicaern/.pyenv/versions/3.10.4/lib/python3.10/site-packages/promptflow_vectordb/core/logging/utils.py", line 97, in wrapper
    res = func(*args, **kwargs)
  File "/Users/jessicaern/.pyenv/versions/3.10.4/lib/python3.10/site-packages/promptflow_vectordb/service/client/embeddingstore_client.py", line 103, in search_by_embedding
    return self.__agent.search_by_embedding(
  File "/Users/jessicaern/.pyenv/versions/3.10.4/lib/python3.10/site-packages/promptflow_vectordb/service/client/agent/cog_search_client.py", line 64, in search_by_embedding
    item.vector = item.original_entity[vector_field]
KeyError: 'content_vector'

Flow test failed with UserErrorException: KeyError: Execution failure in 'vector_search': (KeyError) 'content_vector'
```

**Comment by qiqimico** [comment]
Hi @jessica-ern, we have released promptflow-vectordb==0.1.2 with this issue fixed, you could [pip install promptflow-vectordb](https://pypi.org/project/promptflow-vectordb/) to try it now~
