### ISSUE TITLE
[BUG] Getting unsupported operand type(s) for +: 'dict' and 'dict' when running chat-with-wikipedia flow

### ISSUE THREAD

**Issue by sgahlot** [microsoft/promptflow#3834]
**Describe the bug**
When running `chat-with-wikipedia` flow, I'm encountering the following error:
```
...
  File "/usr/local/lib/python3.9/site-packages/promptflow/tracing/_trace.py", line 145, in <dictcomp>
    key: (self._span_id_to_tokens[parent_span_id].get(key, 0) or 0) + (tokens.get(key, 0) or 0)
TypeError: unsupported operand type(s) for +: 'dict' and 'dict'
```

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1. I used `Open in GitHub Codespaces` option to use the pre-built environment
2. Run the `examples/flows/chat/chat-with-wikipedia` flow, using `Run it with standard mode` option
3. The command I see in the terminal is: `/usr/local/bin/python3 -m promptflow._cli._pf.entry flow test --flow /workspaces/promptflow/examples/flows/chat/chat-with-wikipedia --user-agent "prompt-flow-extension/1.20.2 (linux; x64) VSCode/1.94.2"`
4. The following error comes every single time this flow is run
```
2024-10-25 14:55:25 +0000   17101 execution.flow     INFO     Executing node augmented_chat. node run id: edeaf1be-c107-4555-851f-38d5706e7a30_augmented_chat_0
WARNING:opentelemetry.attributes:Invalid type dict for attribute '__computed__.cumulative_token_count.completion' value. Expected one of ['bool', 'str', 'bytes', 'int', 'float'] or a sequence of those types
WARNING:opentelemetry.attributes:Invalid type dict for attribute '__computed__.cumulative_token_count.prompt' value. Expected one of ['bool', 'str', 'bytes', 'int', 'float'] or a sequence of those types
WARNING:opentelemetry.attributes:Invalid type dict for attribute 'llm.usage.completion_tokens_details' value. Expected one of ['bool', 'str', 'bytes', 'int', 'float'] or a sequence of those types
WARNING:opentelemetry.attributes:Invalid type dict for attribute 'llm.usage.prompt_tokens_details' value. Expected one of ['bool', 'str', 'bytes', 'int', 'float'] or a sequence of those types
WARNING:opentelemetry.attributes:Invalid type dict for attribute '__computed__.cumulative_token_count.completion' value. Expected one of ['bool', 'str', 'bytes', 'int', 'float'] or a sequence of those types
WARNING:opentelemetry.attributes:Invalid type dict for attribute '__computed__.cumulative_token_count.prompt' value. Expected one of ['bool', 'str', 'bytes', 'int', 'float'] or a sequence of those types
2024-10-25 14:55:26 +0000   17101 execution          ERROR    Node augmented_chat in line 0 failed. Exception: Execution failure in 'augmented_chat': (TypeError) unsupported operand type(s) for +: 'dict' and 'dict'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/promptflow/_core/flow_execution_context.py", line 182, in _invoke_tool_inner
    return f(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/promptflow/executor/flow_executor.py", line 1344, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/promptflow/tracing/_trace.py", line 562, in wrapped
    token_collector.collect_openai_tokens_for_parent_span(span)
  File "/usr/local/lib/python3.9/site-packages/promptflow/tracing/_trace.py", line 143, in collect_openai_tokens_for_parent_span
    merged_tokens = {
  File "/usr/local/lib/python3.9/site-packages/promptflow/tracing/_trace.py", line 145, in <dictcomp>
    key: (self._span_id_to_tokens[parent_span_id].get(key, 0) or 0) + (tokens.get(key, 0) or 0)
TypeError: unsupported operand type(s) for +: 'dict' and 'dict'
```

**Expected behavior**
I am expecting the flow to run without any errors

**Screenshots**
I'm attaching two screenshots to show the error
![Image](https://github.com/user-attachments/assets/800f9bab-cd3d-47e8-a896-a47cc863b44c)
![Image](https://github.com/user-attachments/assets/30e64ae1-f38e-4bb6-9a90-94bec81afb0f)

**Running Information(please complete the following information):**
 - Promptflow Package Version using `pf -v`: [e.g. 0.0.102309906]
 ```
{
  "promptflow": "1.16.1",
  "promptflow-azure": "1.16.1",
  "promptflow-core": "1.16.1",
  "promptflow-devkit": "1.16.1",
  "promptflow-tracing": "1.16.1"
}

Executable '/usr/local/bin/python3.9'
Python (Linux) 3.9.20 (main, Oct 19 2024, 01:00:05) 
[GCC 10.2.1 20210110]
```
 - Operating System: Linux (GitHub Codespaces) - `Debian GNU/Linux 11 (bullseye)`
 - Python Version using `python --version`: `Python 3.9.20`

**Additional context**
This is my first time using GitHub Codespaces as well as Prompt flow, so if there's some additional initialization/config that I had to run, please let me know

**Comment by sgahlot** [comment]
I also tried setting the tracing to `none` thinking it won't go to _trace.py but that didn't make any difference but when I set the 
`PF_DISABLE_TRACING` environment variable to `true` then I didn't get this error as the tracing code didn't run in that case.

**Comment by yeamusic21** [comment]
Looks like I had the same, or at least a similar, issue https://github.com/microsoft/promptflow/issues/3850

**Comment by redhatpeter** [comment]
it seems that same issue. 
error message: pf.flow.test failed with UserErrorException: ServiceResponseException: Execution failure in 'qna_multi_agent_step': (ServiceResponseException) ("<class 'semantic_kernel.connectors.ai.open_ai.services.azure_chat_completion.AzureChatCompletion'> service failed to complete the prompt", TypeError("unsupported operand type(s) for +: 'int' and 'dict'"))

command : .venv\Scripts\python.exe -m promptflow._cli._pf.entry flow test --flow c:\Users\leepete\Documents\3.AI-Data\Development\1.2AOAIFeatures\jake-promptflow\flows\semantic_kernel_agent_qna --user-agent "prompt-flow-extension/1.20.2 (win32; x64) VSCode/1.96.0"
{
  "promptflow": "1.16.2",
  "promptflow-azure": "1.16.2",
  "promptflow-core": "1.16.2",
  "promptflow-devkit": "1.16.2",
  "promptflow-tracing": "1.16.2"
}
Python 3.11.7

**Comment by apthagowda97** [comment]
Earlier I used get this as warning, now it changed to error. Any fixes??

**Comment by steve122192** [comment]
{
  "promptflow": "1.16.2",
  "promptflow-azure": "1.16.2",
  "promptflow-core": "1.16.2",
  "promptflow-devkit": "1.16.2",
  "promptflow-tracing": "1.16.2"
}

Python 3.10.15

Error:
in <dictcomp>
    key: (self._span_id_to_tokens[parent_span_id].get(key, 0) or 0) + (tokens.get(key, 0) or 0)
TypeError: unsupported operand type(s) for +: 'int' and 'dict'

**Comment by johnnieskywalker** [comment]
> { "promptflow": "1.16.2", "promptflow-azure": "1.16.2", "promptflow-core": "1.16.2", "promptflow-devkit": "1.16.2", "promptflow-tracing": "1.16.2" }
> 
> Python 3.10.15
> 
> Error: in key: (self._span_id_to_tokens[parent_span_id].get(key, 0) or 0) + (tokens.get(key, 0) or 0) TypeError: unsupported operand type(s) for +: 'int' and 'dict'

in `flow.dag.yaml` at the end try


```yaml
environment_variables:
  PF_DISABLE_TRACING: true
environment:
  python_requirements_txt: requirements.txt
```

**Comment by steve122192** [comment]
> > { "promptflow": "1.16.2", "promptflow-azure": "1.16.2", "promptflow-core": "1.16.2", "promptflow-devkit": "1.16.2", "promptflow-tracing": "1.16.2" }
> > Python 3.10.15
> > Error: in key: (self._span_id_to_tokens[parent_span_id].get(key, 0) or 0) + (tokens.get(key, 0) or 0) TypeError: unsupported operand type(s) for +: 'int' and 'dict'
> 
> in `flow.dag.yaml` at the end try
> 
> environment_variables:
>   PF_DISABLE_TRACING: true
> environment:
>   python_requirements_txt: requirements.txt

That gets it to run but I do need the tracing

**Comment by johnnieskywalker** [comment]
> > > { "promptflow": "1.16.2", "promptflow-azure": "1.16.2", "promptflow-core": "1.16.2", "promptflow-devkit": "1.16.2", "promptflow-tracing": "1.16.2" }
> > > Python 3.10.15
> > > Error: in key: (self._span_id_to_tokens[parent_span_id].get(key, 0) or 0) + (tokens.get(key, 0) or 0) TypeError: unsupported operand type(s) for +: 'int' and 'dict'
> > 
> > 
> > in `flow.dag.yaml` at the end try
> > environment_variables:
> > PF_DISABLE_TRACING: true
> > environment:
> > python_requirements_txt: requirements.txt
> 
> That gets it to run but I do need the tracing

I dunno any other fix and this bug exists for months

**Comment by martinmoldrup** [comment]
I get the same issue in our product setup using prompt flow. The issue started happing [UTC]: 12/12/2024, 3:12:59.908 PM
and stopped again 12/13/2024, 12:31:06.007 PM

Then yesterday it started again yesterday 12/18/2024, 2:25:49.819 PM and is still happening. 

In the code I have two calls to gpt-4o-mini. Interesting the issue always happens on line 48, and not on 45 that also calls the same model. (see screenshot)
![Image](https://github.com/user-attachments/assets/78be41fb-d1ff-4d7f-ae29-b7bcedd37f73)

Runtime: mcr.microsoft.com/azureml/promptflow/promptflow-runtime-stable:20241126.v3

Traceback (most recent call last):
File "/azureml-envs/prompt-flow/runtime/lib/python3.9/site-packages/opentelemetry/trace/__init__.py", line 570, in use_span
yield span
File "/azureml-envs/prompt-flow/runtime/lib/python3.9/site-packages/opentelemetry/sdk/trace/__init__.py", line 1091, in start_as_current_span
yield span
File "/azureml-envs/prompt-flow/runtime/lib/python3.9/site-packages/promptflow/tracing/_trace.py", line 98, in start_as_current_span
yield span
File "/azureml-envs/prompt-flow/runtime/lib/python3.9/site-packages/promptflow/tracing/_trace.py", line 556, in wrapped
output = func(*args, **kwargs)
File "/var/azureml-app/azureml-models/productrag/12/flow_chat_product_companion/tool_rewrite_query.py", line 76, in tool_rewrite_query
rewrite = rewrite_query_InfoCQR(connection, question, chat_history)
File "/var/azureml-app/azureml-models/productrag/12/flow_chat_product_companion/tool_rewrite_query.py", line 45, in rewrite_query_InfoCQR
rewrite_edit = prompt2(question=question, chat_history=chat_history, rewrite=rewrite)
File "/azureml-envs/prompt-flow/runtime/lib/python3.9/site-packages/promptflow/tracing/_trace.py", line 561, in wrapped
token_collector.collect_openai_tokens_for_parent_span(span)
File "/azureml-envs/prompt-flow/runtime/lib/python3.9/site-packages/promptflow/tracing/_trace.py", line 143, in collect_openai_tokens_for_parent_span
merged_tokens = {
File "/azureml-envs/prompt-flow/runtime/lib/python3.9/site-packages/promptflow/tracing/_trace.py", line 144, in <dictcomp>
key: self._span_id_to_tokens[parent_span_id].get(key, 0) + tokens.get(key, 0)
TypeError: unsupported operand type(s) for +: 'int' and 'dict'

**Comment by johnnieskywalker** [comment]
I worked it around by not using tracing on deployed endpoints I added additional loggers in python files

**Comment by mallikarjun-malli** [comment]
https://microsoft.github.io/promptflow/reference/changelog/promptflow-tracing.html shows that this issue was fixed in 
![Image](https://github.com/user-attachments/assets/1c02a54f-8fa3-45bd-b630-61609e27ee58)

Where is this release available?
Looks like it is not yet published.

**Comment by apthagowda97** [comment]
Use the below code in Managed Online Deployment Yaml to disable tracing in v1.16.2 Promptflow for quick fix.
```
environment_variables:
  PF_DISABLE_TRACING: "true"
```

**Comment by steve122192** [comment]
> I get the same issue in our production environment using prompt flow. The issue started happing [UTC]: 12/12/2024, 3:12:59.908 PM and stopped again 12/13/2024, 12:31:06.007 PM
> 
> Then yesterday it started again yesterday 12/18/2024, 2:25:49.819 PM and is still happening.
> 
> In the code I have two calls to gpt-4o-mini. Interesting the issue always happens on line 48, and not on 45 that also calls the same model. (see screenshot) ![Image](https://github.com/user-attachments/assets/78be41fb-d1ff-4d7f-ae29-b7bcedd37f73)
> 
> Runtime: mcr.microsoft.com/azureml/promptflow/promptflow-runtime-stable:20241126.v3
> 
> Traceback (most recent call last): File "/azureml-envs/prompt-flow/runtime/lib/python3.9/site-packages/opentelemetry/trace/**init**.py", line 570, in use_span yield span File "/azureml-envs/prompt-flow/runtime/lib/python3.9/site-packages/opentelemetry/sdk/trace/**init**.py", line 1091, in start_as_current_span yield span File "/azureml-envs/prompt-flow/runtime/lib/python3.9/site-packages/promptflow/tracing/_trace.py", line 98, in start_as_current_span yield span File "/azureml-envs/prompt-flow/runtime/lib/python3.9/site-packages/promptflow/tracing/_trace.py", line 556, in wrapped output = func(*args, **kwargs) File "/var/azureml-app/azureml-models/productrag/12/flow_chat_product_companion/tool_rewrite_query.py", line 76, in tool_rewrite_query rewrite = rewrite_query_InfoCQR(connection, question, chat_history) File "/var/azureml-app/azureml-models/productrag/12/flow_chat_product_companion/tool_rewrite_query.py", line 45, in rewrite_query_InfoCQR rewrite_edit = prompt2(question=question, chat_history=chat_history, rewrite=rewrite) File "/azureml-envs/prompt-flow/runtime/lib/python3.9/site-packages/promptflow/tracing/_trace.py", line 561, in wrapped token_collector.collect_openai_tokens_for_parent_span(span) File "/azureml-envs/prompt-flow/runtime/lib/python3.9/site-packages/promptflow/tracing/_trace.py", line 143, in collect_openai_tokens_for_parent_span merged_tokens = { File "/azureml-envs/prompt-flow/runtime/lib/python3.9/site-packages/promptflow/tracing/_trace.py", line 144, in key: self._span_id_to_tokens[parent_span_id].get(key, 0) + tokens.get(key, 0) TypeError: unsupported operand type(s) for +: 'int' and 'dict'

Interesting, I was having no problems until yesterday as well

**Comment by eses-wk** [comment]
I'm using gpt-4o, also sees this issue. It happens when I am running multiple "Python" Promptflow block each with AsyncAzureOpenai client calling the chat completion API. 

Suspect it is some conflict between Promptflow Tracing and the internal thread pooling handling when gathering multiple OpenAI async calls at the same time.

Disabling Tracing in `flow.dag.yaml` per @johnnieskywalker mentioned works well for me

**Comment by Turki25** [comment]
I used the Azure AI Foundry web interface (I believe it was previously called Azure AI Studio). If you're encountering the same issue, simply disable the Inferencing data collection during deployment, as shown in the screenshot below.

That's the only thing I did, and it worked for me.

<img width="1059" alt="Image" src="https://github.com/user-attachments/assets/faae38fc-a185-45f1-a22b-19d33781d531" />

**Comment by HRNPH** [comment]
is there a work around to still use trace? as I am using trace for my evaluation workflow.

**Comment by jackdgolding** [comment]
Upgrading all promptflow packages to the Jan 6th release, promptflow 1.17.0, fixed the issue for me. The fix is in the release notes.
https://pypi.org/project/promptflow/1.17.0/

**Comment by mariuskempf** [comment]
For me the issue persists although I am on the 1.17 versions. 

```bash
WARNING:opentelemetry.attributes:Invalid type dict for attribute '__computed__.cumulative_token_count.completion' value. Expected one of ['bool', 'str', 'bytes', 'int', 'float'] or a sequence of those types
WARNING:opentelemetry.attributes:Invalid type dict for attribute '__computed__.cumulative_token_count.prompt' value. Expected one of ['bool', 'str', 'bytes', 'int', 'float'] or a sequence of those types
WARNING:opentelemetry.attributes:Invalid type dict for attribute 'llm.usage.completion_tokens_details' value. Expected one of ['bool', 'str', 'bytes', 'int', 'float'] or a sequence of those types
WARNING:opentelemetry.attributes:Invalid type dict for attribute 'llm.usage.prompt_tokens_details' value. Expected one of ['bool', 'str', 'bytes', 'int', 'float'] or a sequence of those types
WARNING:opentelemetry.attributes:Invalid type dict for attribute '__computed__.cumulative_token_count.completion' value. Expected one of ['bool', 'str', 'bytes', 'int', 'float'] or a sequence of those types
WARNING:opentelemetry.attributes:Invalid type dict for attribute '__computed__.cumulative_token_count.prompt' value. Expected one of ['bool', 'str', 'bytes', 'int', 'float'] or a sequence of those types
```

`pf --versions`
```json
{
  "promptflow": "1.17.0",
  "promptflow-azure": "1.17.0",
  "promptflow-core": "1.17.0",
  "promptflow-devkit": "1.17.0",
  "promptflow-tracing": "1.17.0"
}
```

I don't know if this matters, but this was run locally (not Azure ML).
