### ISSUE TITLE
[BUG] [VSCode Extension] [DAG] Visual Editor not loading

### ISSUE THREAD

**Issue by dferrari-cit** [microsoft/promptflow#3879]
**Describe the bug**
The visual editor is not loading

**How To Reproduce the bug**
1. Install the extension
2. Create an empty flow
3. Open the flow

**Expected behavior**
- Extension Host
2024-12-02 10:49:16.785 [info] Extension host terminating: renderer closed the MessagePort
2024-12-02 10:49:16.805 [error] An error occurred when disposing the subscriptions for extension 'prompt-flow.prompt-flow':
2024-12-02 10:49:16.805 [error] Error: Method not implemented.
	at X_t.dispose (c:\Users\user_name\.vscode\extensions\prompt-flow.prompt-flow-1.20.2\extension.js:34210:18640)
	at c:\Users\user_name\.vscode\extensions\prompt-flow.prompt-flow-1.20.2\extension.js:34210:32337
	at Map.forEach (<anonymous>)
	at t.dispose (c:\Users\user_name\.vscode\extensions\prompt-flow.prompt-flow-1.20.2\extension.js:34210:32323)
	at Object.dispose (c:\Users\user_name\.vscode\extensions\prompt-flow.prompt-flow-1.20.2\extension.js:34210:32712)
	at ci (file:///c:/Users/user_name/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:24:699)
	at file:///c:/Users/user_name/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:118:14992
	at file:///c:/Users/user_name/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:24:1009
	at Object.dispose (file:///c:/Users/user_name/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:7:2146)
	at z_.eb (file:///c:/Users/user_name/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:118:11919)
	at file:///c:/Users/user_name/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:118:9874
	at Array.map (<anonymous>)
	at z_.$ (file:///c:/Users/user_name/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:118:9862)
	at z_.terminate (file:///c:/Users/user_name/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:118:10105)
	at EC.terminate (file:///c:/Users/user_name/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:119:1424)
	at Zi (file:///c:/Users/user_name/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:174:15084)
	at MessagePortMain.<anonymous> (file:///c:/Users/user_name/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:174:11632)
	at MessagePortMain.emit (node:events:519:28)
	at MessagePortMain.emit (node:domain:488:12)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2949)
2024-12-02 10:49:16.810 [info] Extension host with pid 21176 exiting with code 0
2024-12-02 10:49:18.100 [info] Extension host with pid 28412 started
2024-12-02 10:49:18.100 [info] Skipping acquiring lock for c:\Users\user_name\AppData\Roaming\Code\User\workspaceStorage\3abad7a72a8babb5d63f2d368482b001.

**Screenshots**
-VSCode
![Image](https://github.com/user-attachments/assets/50082b2e-838a-4c02-9112-55858ceb23b0)

-Error in Devepoler Tools
![Image](https://github.com/user-attachments/assets/6fb656d6-db40-47d8-8c5c-5ca97613f8c5)

**Running Information(please complete the following information):**
Version: 1.95.3 (user setup)
Commit: f1a4fb101478ce6ec82fe9627c43efbf9e98c813
Date: 2024-11-13T14:50:04.152Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.22631

pf -v
{
  "promptflow": "1.16.2",
  "promptflow-core": "1.16.2",
  "promptflow-devkit": "1.16.2",
  "promptflow-tracing": "1.16.2"
}

Python (Windows) 3.11.9

Prompt flow for VS Code - v1.20.2

**Comment by Siu-Keung** [comment]
Same problem too.

**Comment by Siu-Keung** [comment]
Any good news on this issue?
