### ISSUE TITLE
[BUG] Error when deploying online-endpoint for basic-chat

### ISSUE THREAD

**Issue by ouphi** [microsoft/promptflow#666]
**Describe the bug**
I followed [this tutorial](https://learn.microsoft.com/en-us/azure/machine-learning/prompt-flow/how-to-deploy-to-code?view=azureml-api-2&tabs=managed) to deploy an online-endpoint from the basic-chat promptflow. When calling the endpoint I get the following error:

```txt
[2023-09-28 12:40:01]  [23] promptflow-runtime INFO     Try loading connections...
[2023-09-28 12:40:01]  [23] promptflow-runtime INFO     Promptflow serving runtime start getting connections from workspace...
[2023-09-28 12:40:01]  [23] promptflow-runtime INFO     Reading flow from model ...
[2023-09-28 12:40:01]  [23] promptflow-runtime INFO     Getting connection names for flow ...
[2023-09-28 12:40:01]  [23] promptflow-runtime INFO     Getting connection from workspace and build dict for flow ... connection names: {'open_ai_connection'}
[2023-09-28 12:40:01]  [23] promptflow-runtime INFO     Promptflow serving runtime get connections successfully. keys: dict_keys(['open_ai_connection'])
[2023-09-28 12:40:01]  [23] promptflow-runtime INFO     Loading flow...
[2023-09-28 12:40:01]  [23] promptflow-runtime ERROR    Promptflow serving app error: {'code': 'SystemError', 'message': "'NoneType' object has no attribute 'inputs'", 'messageFormat': '', 'messageParameters': {}, 'innerError': {'code': 'AttributeError', 'innerError': None}}
[2023-09-28 12:40:01]  [23] promptflow-runtime ERROR    Promptflow serving error traceback: Traceback (most recent call last):
  File "/azureml-envs/prompt-flow/runtime/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/azureml-envs/prompt-flow/runtime/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/azureml-envs/prompt-flow/runtime/lib/python3.9/site-packages/promptflow/runtime/serving/app.py", line 196, in score
    flow = app.flow_invoker.flow
  File "/azureml-envs/prompt-flow/runtime/lib/python3.9/site-packages/promptflow/runtime/serving/flow_invoker.py", line 107, in flow
    self._try_load()
  File "/azureml-envs/prompt-flow/runtime/lib/python3.9/site-packages/promptflow/runtime/serving/flow_invoker.py", line 115, in _try_load
    self._executor = self.create_flow_executor_by_model(flow_file=self._flow_file, connections=connections)
  File "/azureml-envs/prompt-flow/runtime/lib/python3.9/site-packages/promptflow/runtime/serving/flow_invoker.py", line 143, in create_flow_executor_by_model
    return self.create_flow_executor_by_yaml(flow_file, connections, node_overrides=node_overrides)
  File "/azureml-envs/prompt-flow/runtime/lib/python3.9/site-packages/promptflow/runtime/serving/flow_invoker.py", line 155, in create_flow_executor_by_yaml
    flow = FlowRequestValidator.ensure_flow_valid(flow, connections)
  File "/azureml-envs/prompt-flow/runtime/lib/python3.9/site-packages/promptflow/runtime/serving/flow_request_validator.py", line 119, in ensure_flow_valid
    flow = cls.resolve_llm_connections(flow, connections)
  File "/azureml-envs/prompt-flow/runtime/lib/python3.9/site-packages/promptflow/runtime/serving/flow_request_validator.py", line 102, in resolve_llm_connections
    updated_nodes = [
  File "/azureml-envs/prompt-flow/runtime/lib/python3.9/site-packages/promptflow/runtime/serving/flow_request_validator.py", line 103, in <listcomp>
    cls.resolve_node_llm_connection(tools[node.tool], node, connection_manager) for node in flow.nodes
  File "/azureml-envs/prompt-flow/runtime/lib/python3.9/site-packages/promptflow/runtime/serving/flow_request_validator.py", line 69, in resolve_node_llm_connection
    for key, input in tool_def.inputs.items():
AttributeError: 'NoneType' object has no attribute 'inputs'
```
**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1. Follow [this tutorial](https://learn.microsoft.com/en-us/azure/machine-learning/prompt-flow/how-to-deploy-to-code?view=azureml-api-2&tabs=managed).

**Expected behavior**
The endpoint should work

**Screenshots**

**Running Information(please complete the following information):**
 - Promptflow Package Version: 20230919.v1

**Additional context**
Looks like adding these options to the node fix the issue:
```yaml
  provider: AzureOpenAI
  module: promptflow.tools.aoai
```

**Comment by brynn-code** [comment]
@ouphi I notice the base image in the managed online endpoint yaml is a little old, it's:
![image](https://github.com/microsoft/promptflow/assets/24237253/3d66a8d9-a369-4266-9d91-f13a04c8eea4)
Could you please try with:
mcr.microsoft.com/azureml/promptflow/promptflow-runtime:latest ?
I guess the 0831 version didn't pick this pr: https://github.com/microsoft/promptflow/pull/204/files . which supports run llm node without 'provider' and 'module'.

If so, we will contact the doc owner to update the image in it.

**Comment by ouphi** [comment]
Thank you @brynn-code ! It works for me.
