### ISSUE TITLE
[BUG] Calling a Promptflow from within a promptflow fails with: NotImplementedError: Cannot set active since there is another active instance: <promptflow._core.tracer.Tracer object at 0x7f7b4bf50a00>

### ISSUE THREAD

**Issue by danielsc** [microsoft/promptflow#671]
**Describe the bug**
Calling a PF from a Python Node of a PF fails with `NotImplementedError: Cannot set active since there is another active instance: <promptflow._core.tracer.Tracer object at 0x7f7b4bf50a00>`

**How To Reproduce the bug**
Create a promptflow with a python node that calls another promptflow like so

```python
import os
from promptflow import tool
import promptflow as pf
from promptflow.connections import AzureOpenAIConnection

@tool
def call_eval_flows(
    question: str,
    answer: str,
    context: str,
    azure_open_ai_connection: AzureOpenAIConnection
) -> dict:
    # get folder of the current file
    current_folder = os.path.dirname(os.path.abspath(__file__))
    coherence_flow = os.path.join(current_folder, "coherence")
    fluency_flow = os.path.join(current_folder, "fluency")
    groundedness_flow = os.path.join(current_folder, "groundedness")
    relevance_flow = os.path.join(current_folder, "relevance")

    cli = pf.PFClient()
    coherence = cli.test(coherence_flow, inputs={"question": question, "answer": answer})
    fluency = cli.test(fluency_flow, inputs={"question": question, "answer": answer})
    groundedness = cli.test(groundedness_flow, inputs={"question": question, "answer": answer, "context": context})
    relevance = cli.test(relevance_flow, inputs={"question": question, "answer": answer, "context": context})

    return {"coherence": coherence, "fluency": fluency, "groundedness": groundedness, "relevance": relevance}
```

Run the promptflow with `pf flow test ...` and you will see this error
```
(rag-promptflow) (base) danielsc@Daniels-MBP-M1 eval_flows % /usr/local/Caskroom/miniconda/base/envs/rag-promptflow/bin/python -m promptflo
w._cli._pf.entry flow test --flow /Users/danielsc/git/rag-promptflow/src/eval_flows
Class WorkspaceHubOperations: This is an experimental class, and may change at any time. Please see https://aka.ms/azuremlexperimental for more information.
2023-10-04 10:21:59 +0200   90736 execution          INFO     Start to run 1 nodes with concurrency level 16.
2023-10-04 10:21:59 +0200   90736 execution.flow     INFO     Executing node call_eval_flows. node run id: a0e581d3-c2af-43ae-a291-23c2244c8f22_call_eval_flows_0
2023-10-04 10:22:05 +0200   90736 execution          INFO     Start to run 2 nodes with concurrency level 16.
2023-10-04 10:22:05 +0200   90736 execution.flow     INFO     Executing node coherence_score. node run id: 7eed32a7-b70f-4aa8-b740-a66a5674d21b_coherence_score_0
2023-10-04 10:22:05 +0200   90736 execution          ERROR    Node coherence_score in line 0 failed. Exception: Cannot set active since there is another active instance: <promptflow._core.tracer.Tracer object at 0x7f7b4bf50a00>.
Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/envs/rag-promptflow/lib/python3.10/site-packages/promptflow/_core/flow_execution_context.py", line 123, in invoke_tool_with_cache
    Tracer.start_tracing(node_run_id)
  File "/usr/local/Caskroom/miniconda/base/envs/rag-promptflow/lib/python3.10/site-packages/promptflow/_core/tracer.py", line 33, in start_tracing
    tracer._activate_in_context()
  File "/usr/local/Caskroom/miniconda/base/envs/rag-promptflow/lib/python3.10/site-packages/promptflow/_core/thread_local_singleton.py", line 28, in _activate_in_context
    raise NotImplementedError(f"Cannot set active since there is another active instance: {instance}")
NotImplementedError: Cannot set active since there is another active instance: <promptflow._core.tracer.Tracer object at 0x7f7b4bf50a00>
2023-10-04 10:22:05 +0200   90736 execution          ERROR    One node execution failed, cancel all running tasks. coherence_score.
2023-10-04 10:22:05 +0200   90736 execution          ERROR    Node call_eval_flows in line 0 failed. Exception: Exception: Cannot set active since there is another active instance: <promptflow._core.tracer.Tracer object at 0x7f7b4bf50a00>.
Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/envs/rag-promptflow/lib/python3.10/site-packages/promptflow/_core/flow_execution_context.py", line 126, in invoke_tool_with_cache
    result = self.invoke_tool(f, args, kwargs)
  File "/usr/local/Caskroom/miniconda/base/envs/rag-promptflow/lib/python3.10/site-packages/promptflow/_core/flow_execution_context.py", line 170, in invoke_tool
    raise e
  File "/usr/local/Caskroom/miniconda/base/envs/rag-promptflow/lib/python3.10/site-packages/promptflow/_core/flow_execution_context.py", line 164, in invoke_tool
    return f(*args, **kwargs)
  File "/Users/danielsc/git/rag-promptflow/src/eval_flows/call_eval_flows.py", line 27, in call_eval_flows
    coherence = cli.test(coherence_flow, inputs={"question": question, "answer": answer})
  File "/usr/local/Caskroom/miniconda/base/envs/rag-promptflow/lib/python3.10/site-packages/promptflow/_sdk/_pf_client.py", line 228, in test
    return self.flows.test(
  File "/usr/local/Caskroom/miniconda/base/envs/rag-promptflow/lib/python3.10/site-packages/promptflow/_sdk/operations/_flow_operations.py", line 67, in test
    TestSubmitter._raise_error_when_test_failed(result, show_trace=node is not None)
  File "/usr/local/Caskroom/miniconda/base/envs/rag-promptflow/lib/python3.10/site-packages/promptflow/_sdk/operations/_test_submitter.py", line 354, in _raise_error_when_test_failed
    raise UserErrorException(f"{error_type}: {error_message}")
promptflow.exceptions.UserErrorException: Exception: Cannot set active since there is another active instance: <promptflow._core.tracer.Tracer object at 0x7f7b4bf50a00>
2023-10-04 10:22:05 +0200   90736 execution          ERROR    One node execution failed, cancel all running tasks. call_eval_flows.
Flow test failed with UserErrorException: Exception: list index out of range
```

**Expected behavior**
Customers would like to combine multiple promptflows into larger ones, for instance when running multiple evals into one run but also in more general composition scenarios. 

**Running Information(please complete the following information):**
 - Promptflow Package Version using `pf -v`: 0.1.0b7.post1
 - Operating System: MacOS X 13.5.2 (22G91)
 - Python Version using `python --version`: Python 3.10.4

**Comment by thy09** [comment]
Hi @danielsc , the issue `Cannot set active since there is another active instance` is resolved in the latest version, can you check whether your scenario is unblocked?
