### ISSUE TITLE
[BUG] PFClient doesn't take the azureml connection config

### ISSUE THREAD

**Issue by luigiw** [microsoft/promptflow#961]
**Describe the bug**
A clear and concise description of the bug.

When I set connection.provider to an azureml workspace, I expect `pf_client.test()` to be able to use connections in my azureml workspace, but it isn't the case.

**How To Reproduce the bug**
Steps to reproduce the behavior, how frequent can you experience the bug:
1. Initiate a PFClient with azureml connection config
```python
    pf_client = PFClient(config={"connection.provider": "azureml:"
                + RESOURCE_ID_FORMAT.format(
                    os.environ["AZURE_SUBSCRIPTION_ID"], os.environ["AZURE_RESOURCE_GROUP"], AZUREML_RESOURCE_PROVIDER, os.environ["AZURE_AI_PROJECT_NAME"]
                )})
```
2. List connections an observe that my azureml connections are listed.

```
name: Default_CognitiveSearch
module: promptflow.connections
created_date: '2023-10-17 18:24:37.387043+00:00'
last_modified_date: '2023-10-17 18:24:37.387043+00:00'
type: cognitive_search
api_key: '******'
api_base: https://xxx
api_version: dummy

name: Default_AzureOpenAI
module: promptflow.connections
type: azure_open_ai
api_key: '******'
api_base: https://yyy
api_type: Azure
api_version: 2023-03-15-preview
```

3. Run pf_client.test() with a local flow that references a remote connection and observe the error.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/promptflow/_sdk/_utils.py", line 815, in get_local_connections_from_executable
    conn = client.connections.get(name=n, with_secrets=True)
  File "/usr/local/lib/python3.10/site-packages/promptflow/_telemetry/activity.py", line 138, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/promptflow/_sdk/operations/_connection_operations.py", line 54, in get
    orm_connection = ORMConnection.get(name, raise_error)
  File "/usr/local/lib/python3.10/site-packages/promptflow/_sdk/_orm/retry.py", line 43, in f_retry
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/promptflow/_sdk/_orm/connection.py", line 52, in get
    raise ConnectionNotFoundError(f"Connection {name!r} is not found.")
promptflow._sdk._errors.ConnectionNotFoundError: Connection 'Default_AzureOpenAI' is not found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspaces/aistudio-copilot-sample/src/run.py", line 202, in <module>
    result = asyncio.run(
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/workspaces/aistudio-copilot-sample/src/copilot_promptflow/chat.py", line 21, in chat_completion
    result = pf_client.test(flow="src/copilot_promptflow", inputs=inputs)
  File "/usr/local/lib/python3.10/site-packages/promptflow/_sdk/_pf_client.py", line 234, in test
    return self.flows.test(
  File "/usr/local/lib/python3.10/site-packages/promptflow/_telemetry/activity.py", line 138, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/promptflow/_sdk/operations/_flow_operations.py", line 71, in test
    result = self._test(
  File "/usr/local/lib/python3.10/site-packages/promptflow/_sdk/operations/_flow_operations.py", line 127, in _test
    return submitter.flow_test(
  File "/usr/local/lib/python3.10/site-packages/promptflow/_sdk/operations/_test_submitter.py", line 152, in flow_test
    connections = SubmitterHelper.resolve_connections(flow=self.flow, client=self._client)
  File "/usr/local/lib/python3.10/site-packages/promptflow/_sdk/operations/_run_submitter.py", line 216, in resolve_connections
    return get_local_connections_from_executable(executable=executable, client=client)
  File "/usr/local/lib/python3.10/site-packages/promptflow/_sdk/_utils.py", line 819, in get_local_connections_from_executable
    raise Exception(f"Connection {n!r} required for flow {executable.name!r} is not found.")
Exception: Connection 'Default_AzureOpenAI' required for flow 'copilot_promptflow' is not found.
```

**Running Information(please complete the following information):**
 - Promptflow Package Version using `pf -v`: [e.g. 0.0.102309906]
 - Operating System: [e.g. Ubuntu 20.04, Windows 11]
 - Python Version using `python --version`: [e.g. python==3.10.12]

```
Name: promptflow
Version: 0.1.0b8
Summary: Prompt flow Python SDK - build high-quality LLM apps
Home-page: https://github.com/microsoft/promptflow
Author: Microsoft Corporation
Author-email: aml-pt-eng@microsoft.com
License: MIT License
Location: /usr/local/lib/python3.10/site-packages
Requires: colorama, cryptography, dataset, filelock, flask, gitpython, keyring, marshmallow, openai, opencensus-ext-azure, pandas, pillow, psutil, pyarrow, pydash, python-dotenv, pyyaml, ruamel.yaml, sqlalchemy, strictyaml, tabulate, tiktoken, waitress
Required-by: promptflow-tools
```

**Additional context**

**Comment by brynn-code** [comment]
Ack, will check this soon.

**Comment by brynn-code** [comment]
Confirmed this is a bug, will fix and trigger an internal release to unblock you.

**Comment by brynn-code** [comment]
Please try with `pip install promptflow==109137057 --extra-index-url https://azuremlsdktestpypi.azureedge.net/promptflow`, feel free to ping me if anything doesn't work as expected.
